### PR TITLE
Upgrade lambda runtime to python3.12

### PR DESCRIPTION
**Pull request by armona**
AWS announced they are ending support for Python 3.8 in Lambda on October 14, 2024. This follows Python 3.8 End-Of-Life which is scheduled October, 2024.

### CODE REVIEW

**Comment by bwhaley** [comment]
Thank you! The tests pass but had some deprecation warnings, so I fixed those. I'm going to do a little more testing before merging this.

**Comment by armona** [comment]
@bwhaley Thanks!

We are going to test it in our dev environment tomorrow as well.

**Comment by bwhaley** [comment]
So far so good using both container and the python runtime.

**Review by bwhaley — APPROVED** [review]

**Comment by armona** [comment]
I can confirm that also in our test environment, lambda execution are ok.

**Comment by bwhaley** [comment]
Released in v0.5.0.

**Pull request merged**
